import { Key } from "lucide-react";

export const works = [
  {
    id: 1,
    title: "Digital Dreamscape",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 2,
    title: "Abstract Harmony",
    category: "profil",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 3,
    title: "Metal Flow",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 4,
    title: "Neon Nights",
    category: "kegiatan",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 5,
    title: "Nature's Whisper",
    category: "profil",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2024",
  },
  {
    id: 6,
    title: "Bronze Echo",
    category: "kajian",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2023",
  },
  {
    id: 7,
    title: "Digital Dreamscape",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 8,
    title: "Abstract Harmony",
    category: "profil",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 9,
    title: "Metal Flow",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 10,
    title: "Neon Nights",
    category: "kegiatan",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 11,
    title: "Nature's Whisper",
    category: "profil",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2024",
  },
  {
    id: 12,
    title: "Bronze Echo",
    category: "kajian",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2023",
  },
];

// export const lapakData = [
//   { id: 1, nama: 'Jasa Servis AC Profesional', harga: 150000, kategori: 'Jasa', subkategori: 'Elektronik', terjual: 150, rating: 5, penjual: 'AC Dingin Selalu', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/3498db/ffffff?text=Servis+AC' },
//   { id: 2, nama: 'Tisu Wajah Halus (Paket 10)', harga: 34999, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 500, rating: 5, penjual: 'Toko Barokah', lokasi: 'Jakarta Timur', gambar: 'https://placehold.co/600x600/2ecc71/ffffff?text=Tisu+Paket' },
//   { id: 3, nama: 'Nasi Kebuli Lezat (Porsi Besar)', harga: 45000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 300, rating: 5, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e74c3c/ffffff?text=Nasi+Kebuli' },
//   { id: 4, nama: 'Jasa Montir Panggilan', harga: 250000, kategori: 'Jasa', subkategori: 'Kendaraan', terjual: 80, rating: 5, penjual: 'Montir Cepat', lokasi: 'Jakarta Pusat', gambar: 'https://placehold.co/600x600/f1c40f/ffffff?text=Montir' },
//   { id: 5, nama: 'Air Mineral Markaz (Kardus)', harga: 25000, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 1000, rating: 5, penjual: 'Koperasi Markaz', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/9b59b6/ffffff?text=Air+Mineral' },
//   { id: 6, nama: 'Jasa Desain Logo & Branding', harga: 500000, kategori: 'Jasa', subkategori: 'Kreatif', terjual: 50, rating: 5, penjual: 'Desain Keren', lokasi: 'Online', gambar: 'https://placehold.co/600x600/1abc9c/ffffff?text=Desain+Logo' },
//   { id: 7, nama: 'Kue Kering Lebaran (Toples)', harga: 85000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 250, rating: 4.8, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e67e22/ffffff?text=Kue+Kering' },
//   { id: 8, nama: 'Jasa Cuci Karpet Masjid', harga: 10000, kategori: 'Jasa', subkategori: 'Kebersihan', terjual: 120, rating: 4.9, penjual: 'Berkah Clean', lokasi: 'Depok' , gambar: 'https://placehold.co/600x600/34495e/ffffff?text=Cuci+Karpet'},{ id: 1, nama: 'Jasa Servis AC Profesional', harga: 150000, kategori: 'Jasa', subkategori: 'Elektronik', terjual: 150, rating: 4.9, penjual: 'AC Dingin Selalu', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/3498db/ffffff?text=Servis+AC' },
//   { id: 9, nama: 'Tisu Wajah Halus (Paket 10)', harga: 34999, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 500, rating: 4.8, penjual: 'Toko Barokah', lokasi: 'Jakarta Timur', gambar: 'https://placehold.co/600x600/2ecc71/ffffff?text=Tisu+Paket' },
//   { id: 10, nama: 'Nasi Kebuli Lezat (Porsi Besar)', harga: 45000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 300, rating: 5.0, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e74c3c/ffffff?text=Nasi+Kebuli' },
//   { id: 11, nama: 'Jasa Montir Panggilan', harga: 250000, kategori: 'Jasa', subkategori: 'Kendaraan', terjual: 80, rating: 4.7, penjual: 'Montir Cepat', lokasi: 'Jakarta Pusat', gambar: 'https://placehold.co/600x600/f1c40f/ffffff?text=Montir' },
//   { id: 12, nama: 'Air Mineral Markaz (Kardus)', harga: 25000, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 1000, rating: 4.9, penjual: 'Koperasi Markaz', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/9b59b6/ffffff?text=Air+Mineral' },
//   { id: 13, nama: 'Jasa Desain Logo & Branding', harga: 500000, kategori: 'Jasa', subkategori: 'Kreatif', terjual: 50, rating: 5.0, penjual: 'Desain Keren', lokasi: 'Online', gambar: 'https://placehold.co/600x600/1abc9c/ffffff?text=Desain+Logo' },
//   { id: 14, nama: 'Kue Kering Lebaran (Toples)', harga: 85000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 250, rating: 4.8, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e67e22/ffffff?text=Kue+Kering' },
//   { id: 15, nama: 'Jasa Cuci Karpet Masjid', harga: 10000, kategori: 'Jasa', subkategori: 'Kebersihan', terjual: 120, rating: 4.9, penjual: 'Berkah Clean', lokasi: 'Depok' , gambar: 'https://placehold.co/600x600/34495e/ffffff?text=Cuci+Karpet'},{ id: 1, nama: 'Jasa Servis AC Profesional', harga: 150000, kategori: 'Jasa', subkategori: 'Elektronik', terjual: 150, rating: 4.9, penjual: 'AC Dingin Selalu', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/3498db/ffffff?text=Servis+AC' },
//   { id: 16, nama: 'Tisu Wajah Halus (Paket 10)', harga: 34999, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 500, rating: 4.8, penjual: 'Toko Barokah', lokasi: 'Jakarta Timur', gambar: 'https://placehold.co/600x600/2ecc71/ffffff?text=Tisu+Paket' },
//   { id: 17, nama: 'Nasi Kebuli Lezat (Porsi Besar)', harga: 45000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 300, rating: 5.0, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e74c3c/ffffff?text=Nasi+Kebuli' },
//   { id: 18, nama: 'Jasa Montir Panggilan', harga: 250000, kategori: 'Jasa', subkategori: 'Kendaraan', terjual: 80, rating: 4.7, penjual: 'Montir Cepat', lokasi: 'Jakarta Pusat', gambar: 'https://placehold.co/600x600/f1c40f/ffffff?text=Montir' },
//   { id: 19, nama: 'Air Mineral Markaz (Kardus)', harga: 25000, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 1000, rating: 4.9, penjual: 'Koperasi Markaz', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/9b59b6/ffffff?text=Air+Mineral' },
//   { id: 20, nama: 'Jasa Desain Logo & Branding', harga: 500000, kategori: 'Jasa', subkategori: 'Kreatif', terjual: 50, rating: 5.0, penjual: 'Desain Keren', lokasi: 'Online', gambar: 'https://placehold.co/600x600/1abc9c/ffffff?text=Desain+Logo' },
//   { id: 21, nama: 'Kue Kering Lebaran (Toples)', harga: 85000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 250, rating: 4.8, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e67e22/ffffff?text=Kue+Kering' },
//   { id: 22, nama: 'Jasa Cuci Karpet Masjid', harga: 10000, kategori: 'Jasa', subkategori: 'Kebersihan', terjual: 120, rating: 4.9, penjual: 'Berkah Clean', lokasi: 'Depok' , gambar: 'https://placehold.co/600x600/34495e/ffffff?text=Cuci+Karpet'},{ id: 1, nama: 'Jasa Servis AC Profesional', harga: 150000, kategori: 'Jasa', subkategori: 'Elektronik', terjual: 150, rating: 4.9, penjual: 'AC Dingin Selalu', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/3498db/ffffff?text=Servis+AC' },
//   { id: 23, nama: 'Tisu Wajah Halus (Paket 10)', harga: 34999, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 500, rating: 4.8, penjual: 'Toko Barokah', lokasi: 'Jakarta Timur', gambar: 'https://placehold.co/600x600/2ecc71/ffffff?text=Tisu+Paket' },
//   { id: 24, nama: 'Nasi Kebuli Lezat (Porsi Besar)', harga: 45000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 300, rating: 5.0, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e74c3c/ffffff?text=Nasi+Kebuli' },
//   { id: 25, nama: 'Jasa Montir Panggilan', harga: 250000, kategori: 'Jasa', subkategori: 'Kendaraan', terjual: 80, rating: 4.7, penjual: 'Montir Cepat', lokasi: 'Jakarta Pusat', gambar: 'https://placehold.co/600x600/f1c40f/ffffff?text=Montir' },
//   { id: 26, nama: 'Air Mineral Markaz (Kardus)', harga: 25000, kategori: 'Dagang', subkategori: 'Kebutuhan Harian', terjual: 1000, rating: 4.9, penjual: 'Koperasi Markaz', lokasi: 'Jakarta Selatan', gambar: 'https://placehold.co/600x600/9b59b6/ffffff?text=Air+Mineral' },
//   { id: 27, nama: 'Jasa Desain Logo & Branding', harga: 500000, kategori: 'Jasa', subkategori: 'Kreatif', terjual: 50, rating: 5.0, penjual: 'Desain Keren', lokasi: 'Online', gambar: 'https://placehold.co/600x600/1abc9c/ffffff?text=Desain+Logo' },
//   { id: 28, nama: 'Kue Kering Lebaran (Toples)', harga: 85000, kategori: 'Dagang', subkategori: 'Makanan', terjual: 250, rating: 4.8, penjual: 'Dapur Ummi', lokasi: 'Bekasi', gambar: 'https://placehold.co/600x600/e67e22/ffffff?text=Kue+Kering' },
//   { id: 29, nama: 'Jasa Cuci Karpet Masjid', harga: 10000, kategori: 'Jasa', subkategori: 'Kebersihan', terjual: 120, rating: 4.9, penjual: 'Berkah Clean', lokasi: 'Depok' , gambar: 'https://placehold.co/600x600/34495e/ffffff?text=Cuci+Karpet'},
// ];
