export const works = [
  {
    id: 1,
    title: "Digital Dreamscape",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 2,
    title: "Abstract Harmony",
    category: "profil",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 3,
    title: "Metal Flow",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 4,
    title: "Neon Nights",
    category: "kegiatan",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 5,
    title: "Nature's Whisper",
    category: "profil",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2024",
  },
  {
    id: 6,
    title: "Bronze Echo",
    category: "kajian",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2023",
  },
  {
    id: 7,
    title: "Digital Dreamscape",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 8,
    title: "Abstract Harmony",
    category: "profil",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 9,
    title: "Metal Flow",
    category: "kajian",
    image: "../assets/placeholder.svg",
    year: "2024",
  },
  {
    id: 10,
    title: "Neon Nights",
    category: "kegiatan",
    image: "../assets/placeholder.svg",
    year: "2023",
  },
  {
    id: 11,
    title: "Nature's Whisper",
    category: "profil",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2024",
  },
  {
    id: 12,
    title: "Bronze Echo",
    category: "kajian",
    image: "../assets/placeholder.svg?height=400&width=600",
    year: "2023",
  },
];
